name: Documentation

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
    - name: Generate documentation
      run: |
        uv run pdoc src/mobi_physio_api \
          --docformat google \
          --output-directory docs \
          --html
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v5
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4
